In [1]:
from TextMining_cls_wk_4 import *
from TextMining_twitter_wk_4 import *
import pandas as pd

# (7 points): hashtag predictor. parse, tokens, dictionary and vector to train a classifier for each hashtag. naïve bayes classifier. ‘create_training_data’ and ‘create_testing_data’, ‘compute_accuracy’

In [2]:
(train_data,train_labels,vocab) = create_training_data('TextMining_twitter_train_wk_4.txt')
(test_data, test_labels) = create_testing_data('TextMining_twitter_test_wk_4.txt', vocab)

In [4]:
train_df = pd.concat([pd.DataFrame(train_data), pd.DataFrame(train_labels, columns=['label'])], axis = 1)
train_df.head()

,0,1,2,3,4,5,6,7,8,9,...,903,904,905,906,907,908,909,910,911,label
0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"2,"
1,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"2,"
2,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"2,"
3,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"2,"
4,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"2,"

In [5]:
test_df = pd.concat([pd.DataFrame(test_data), pd.DataFrame(test_labels, columns=['label'])], axis = 1)
test_df.head()

,0,1,2,3,4,5,6,7,8,9,...,903,904,905,906,907,908,909,910,911,label
0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"2,"
1,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"2,"
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"2,"
3,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"2,"
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"2,"

In [6]:
nbClassifier = train_naive_bayes(train_df.drop(columns=['label']), train_df['label'])
nbPred = evaluate_classifier(nbClassifier, test_df.drop(columns=['label']))
compute_accuracy(nbPred, test_df['label'])

TMPY> Training naive bayes
TMPY> Evaluating classifier
correct =  29  incorrect =  35

# (3 points): Run any sample NE extractor on some test data. Why are the results not better than they are?

Statistical NER systems typically require a large amount of manually annotated training data. NER systems developed for one domain do not typically perform well on other domains.

# (5 points): In McCallum and Li, how is domain-specific information integrated in training a statistical NE extractor?

WebListing is used to obtain seeds for the lexicons from the labeled data, then use the Web, HTML formatting regularities and a search engine service to augment those lexicons.